import { ingredientById } from '../data/ingredients'

/** Names short enough to sit around the rim of the wheel on a phone. Anything not listed
 *  here uses its full name, which is already short. */
const SHORT: Record<string, string> = {
  'scotch-blended': 'Scotch',
  'scotch-islay': 'Islay',
  'irish-whiskey': 'Irish',
  'japanese-whisky': 'Japanese',
  'anejo-tequila': 'Añejo',
  'blanco-tequila': 'Blanco',
  'jamaican-rum': 'Jamaican',
  'blackstrap-rum': 'Blackstrap',
  'aged-rum': 'Aged rum',
  'white-rum': 'White rum',
  'rhum-agricole': 'Agricole',
  'old-tom-gin': 'Old Tom',
  'citrus-vodka': 'Citrus vodka',
  gin: 'Gin',
  'sweet-vermouth': 'Sweet verm.',
  'dry-vermouth': 'Dry verm.',
  'bianco-vermouth': 'Bianco',
  'blanc-aperitif': 'Lillet',
  'fino-sherry': 'Fino',
  'amontillado-sherry': 'Amontillado',
  'ruby-port': 'Port',
  'white-wine': 'White wine',
  'red-wine': 'Red wine',
  'orange-bitters': 'Orange bit.',
  peychauds: 'Peychaud’s',
  angostura: 'Angostura',
  fernet: 'Fernet',
  'amaro-nonino': 'Nonino',
  'green-chartreuse': 'Green Char.',
  'yellow-chartreuse': 'Yellow Char.',
  'orange-curacao': 'Curaçao',
  'grand-marnier': 'Grand M.',
  'triple-sec': 'Triple sec',
  'creme-de-cacao': 'Cacao',
  'creme-de-menthe': 'Menthe',
  'creme-de-cassis': 'Cassis',
  'creme-de-mure': 'Mûre',
  'creme-de-violette': 'Violette',
  'cherry-liqueur': 'Cherry liq.',
  'coffee-liqueur': 'Coffee liq.',
  'allspice-dram': 'Allspice',
  'elderflower-liqueur': 'Elderflower',
  'passionfruit-liqueur': 'Passion liq.',
  benedictine: 'Bénédictine',
  'lemon-juice': 'Lemon',
  'lime-juice': 'Lime',
  'grapefruit-juice': 'Grapefruit',
  'orange-juice': 'Orange',
  'pineapple-juice': 'Pineapple',
  'cranberry-juice': 'Cranberry',
  'passionfruit-puree': 'Passion fr.',
  'simple-syrup': 'Simple',
  'demerara-syrup': 'Demerara',
  'honey-syrup': 'Honey',
  'honey-ginger-syrup': 'Honey-ginger',
  'agave-nectar': 'Agave',
  'maple-syrup': 'Maple',
  'raspberry-syrup': 'Raspberry',
  'ginger-syrup': 'Ginger syr.',
  'cane-syrup': 'Cane',
  'vanilla-syrup': 'Vanilla',
  'caster-sugar': 'Sugar',
  'sugar-cube': 'Sugar cube',
  'ginger-root': 'Ginger',
  'orange-flower-water': 'Orange fl.',
  'orange-wheel': 'Orange wheel',
  'egg-white': 'Egg white',
  'whole-egg': 'Whole egg',
  'egg-yolk': 'Egg yolk',
  'heavy-cream': 'Cream',
  'coconut-cream': 'Coconut',
  'soda-water': 'Soda',
  'tonic-water': 'Tonic',
  'ginger-beer': 'Ginger beer',
  'ginger-ale': 'Ginger ale',
  'grapefruit-soda': 'Grapefr. soda',
  'hot-coffee': 'Coffee',
}

export function shortName(id: string): string {
  return SHORT[id] ?? ingredientById[id]?.name ?? id
}

export function fullName(id: string): string {
  return ingredientById[id]?.name ?? id
}

export const ROLE_LABEL: Record<string, string> = {
  core: 'Core',
  balance: 'Balance',
  seasoning: 'Seasoning',
  texture: 'Texture',
}
